version: "3"
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    container_name: backend
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    depends_on:
      - db
    ports:
      - 3001:3000
  web:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: web
    image: "node:14-alpine"
    user: "node"
    working_dir: /myapp/web
    volumes:
      - ./web:/myapp/web
    command: "yarn start"
    depends_on:
      - backend
    ports:
      - 3000:3000
